spring:
#  profiles:
#    active: dev
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/xfan?useUnicode=true&characterEncoding=utf8&characterSetResults=utf8&useSSL=true
    username: root
    password: xfan

  data:
       elasticsearch:
         cluster-name: elasticsearch
         cluster-nodes: 127.0.0.1:9300

  jpa:
      hibernate:
        ddl-auto: update  # 第一次简表create  后面用update
      show-sql: true

  redis:
    host: localhost
    port: 6379
    password:
    database: 0
    pool:
      max-active: 8
      max-wait: -1
      max-idle: 500
      min-idle: 0
    timeout: 0

  thymeleaf:
      prefix: classpath:/templates/


mybatis:
  mapper-locations: classpath:mybatis/mapper/*.xml
  config-location: classpath:mybatis/mybatis-config.xml

my:
  name: xfan
  age: 23
  number: ${random.int}
  uuid: ${random.uuid}
  max: ${random.int(10)}
  value: ${random.value}
  greeting: hi,i`m ${my.name}
